import XCTest
@testable import Lightly

/// Parity with the shared rendering goldens of rendering-v2 revision 3
/// (`shared/fixtures/rendering`, generated by `shared/contracts/make_rendering_goldens.py` from
/// `experiments/depth/refocus.py` and `reference_model.apply_grain`). Tolerances are the ones in
/// `index.json`.
final class RenderingGoldenTests: XCTestCase {

    private static let directory = "shared/fixtures/rendering"

    private static func index() throws -> [String: Any] {
        let data = try Data(contentsOf: DevelopParityTests.fixture("\(directory)/index.json"))
        return try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    /// A little-endian float32 array file.
    private static func floats(_ entry: Any?) throws -> (values: [Float], shape: [Int]) {
        let object = try XCTUnwrap(entry as? [String: Any])
        let name = try XCTUnwrap(object["file"] as? String)
        let shape = try XCTUnwrap(object["shape"] as? [Int])
        let data = try Data(contentsOf: DevelopParityTests.fixture("\(directory)/\(name)"))
        let values: [Float] = data.withUnsafeBytes { raw in
            (0..<(data.count / 4)).map { Float(bitPattern: UInt32(littleEndian: raw.loadUnaligned(fromByteOffset: $0 * 4, as: UInt32.self))) }
        }
        XCTAssertEqual(values.count, shape.reduce(1, *), name)
        return (values, shape)
    }

    private static func image(_ entry: Any?) throws -> FloatImage {
        let (values, shape) = try floats(entry)
        return FloatImage(width: shape[1], height: shape[0], channels: shape.count == 3 ? shape[2] : 1, data: values)
    }

    private var focus: [String: Any] { get throws { try XCTUnwrap(try Self.index()["backgroundFocus"] as? [String: Any]) } }

    // MARK: - Contract

    func testTheGoldensAreRevisionTwoAndTheBundledContractMatches() throws {
        let contract = try XCTUnwrap(try Self.index()["renderingContract"] as? [String: Any])
        XCTAssertEqual(contract["revision"] as? Int, 6)
        let data = try Data(contentsOf: DevelopParityTests.fixture("shared/contracts/rendering-v2.json"))
        XCTAssertNoThrow(try DevelopModel.load(contractData: data), "DevelopModel accepts revision 2 and its focus constants")
        let constants = try XCTUnwrap(try focus["constants"] as? [String: Any])
        XCTAssertEqual((constants["maxBlurRadius"] as? [String: Any])?["value"] as? Double, 0.06)
        XCTAssertEqual(Double(RefocusRenderer.maxCoCFractionOfLongSide), 0.06, accuracy: 1e-7)
        XCTAssertEqual((constants["focusHalfWidthPerUnit"] as? [String: Any])?["value"] as? Double, 0.5)
        XCTAssertEqual(RefocusRenderer.focusHalfWidthPerUnit, 0.5)
        XCTAssertEqual((constants["layersPerSide"] as? [String: Any])?["export"] as? Int, RefocusRenderer.layersPerSide)
    }

    func testAContractOfAnotherRevisionIsRefused() throws {
        var text = try String(contentsOf: DevelopParityTests.fixture("shared/contracts/rendering-v2.json"), encoding: .utf8)
        let range = try XCTUnwrap(text.range(of: "\"revision\": \(DevelopModel.requiredContractRevision)"))
        text.replaceSubrange(range, with: "\"revision\": 0")
        XCTAssertThrowsError(try DevelopModel.load(contractData: Data(text.utf8)))
    }

    // MARK: - Scalars

    func testSignedCoCHalfWidthAndRadius() throws {
        let scalars = try XCTUnwrap(try focus["scalars"] as? [String: Any])
        let cases = try XCTUnwrap(scalars["signedCoc"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 4)
        for item in cases {
            let focal = Float(try XCTUnwrap(item["focal"] as? Double))
            let dof = Float(try XCTUnwrap(item["depthOfField"] as? Double))
            let blur = Float(try XCTUnwrap(item["blur"] as? Double))
            let longEdge = try XCTUnwrap(item["longEdge"] as? Int)
            let h = RefocusRenderer.halfWidth(focusDepth: dof)
            let r = RefocusRenderer.radiusMax(blur: blur, longSide: longEdge)
            XCTAssertEqual(Double(h), try XCTUnwrap(item["halfWidth"] as? Double), accuracy: 1e-4)
            XCTAssertEqual(Double(RefocusRenderer.defocusRange(focal: focal)), try XCTUnwrap(item["defocusRange"] as? Double), accuracy: 1e-4)
            XCTAssertEqual(Double(r), try XCTUnwrap(item["radiusMaxPx"] as? Double), accuracy: 1e-3)
            let disparities = try XCTUnwrap(item["disparity"] as? [Double])
            let expected = try XCTUnwrap(item["signedCocPx"] as? [Double])
            for (d, e) in zip(disparities, expected) {
                let coc = RefocusRenderer.signedCoC(disparity: Float(d), focal: focal, halfWidth: h, radiusMax: r)
                XCTAssertEqual(Double(coc), e, accuracy: 1e-3, "focal \(focal) disparity \(d)")
            }
        }
    }

    func testHighlightExpansion() throws {
        let scalars = try XCTUnwrap(try focus["scalars"] as? [String: Any])
        let highlights = try XCTUnwrap(scalars["highlights"] as? [String: Any])
        let linear = try XCTUnwrap(highlights["linear"] as? [[Double]])
        let expanded = try XCTUnwrap(highlights["expanded"] as? [[Double]])
        var image = FloatImage(width: linear.count, height: 1, channels: 3)
        for (i, rgb) in linear.enumerated() { for c in 0..<3 { image.data[i * 3 + c] = Float(rgb[c]) } }
        let out = RefocusRenderer.expandHighlights(image)
        for (i, rgb) in expanded.enumerated() {
            for c in 0..<3 { XCTAssertEqual(Double(out.data[i * 3 + c]), rgb[c], accuracy: 1e-4) }
        }
        let back = RefocusRenderer.compressHighlights(out)
        for (a, b) in zip(back.data, image.data) { XCTAssertEqual(a, b, accuracy: 1e-4) }
    }

    // MARK: - Kernels

    func testKernels() throws {
        let kernels = try XCTUnwrap(try focus["kernels"] as? [[String: Any]])
        XCTAssertEqual(kernels.count, 10)
        for item in kernels {
            let kind = try XCTUnwrap(item["kind"] as? String)
            let radius = Float(try XCTUnwrap(item["radius"] as? Double))
            let kernel: RefocusRenderer.Kernel
            switch kind {
            case "bokeh":
                let name = try XCTUnwrap(item["file"] as? String)
                let shape = try XCTUnwrap(EditRecipe.Focus.Bokeh.allCases.first { name.contains("-\($0.rawValue)-") })
                kernel = RefocusRenderer.kernel(style: .lens, bokeh: shape, radius: radius, styleAmount: 50)
            case "gaussian":
                kernel = RefocusRenderer.kernel(style: .soft, bokeh: .round, radius: radius, styleAmount: 50)
            case "motion":
                kernel = RefocusRenderer.motionKernel(radius: radius, directionDegrees: Float(try XCTUnwrap(item["directionDegrees"] as? Double)))
            default:
                XCTFail("unknown kernel \(kind)"); continue
            }
            let (values, shape) = try Self.floats(item)
            let matrix = RefocusRenderer.matrix(kernel)
            XCTAssertEqual(matrix.size, shape[0], "\(item["file"] ?? "")")
            guard matrix.size == shape[0] else { continue }
            let worst = zip(matrix.values, values).map { abs($0 - $1) }.max() ?? 1
            XCTAssertLessThanOrEqual(worst, 1e-5, "\(item["file"] ?? "")")
        }
    }

    // MARK: - Pull-push

    func testPullPushFillsLikeTheReference() throws {
        let cases = try XCTUnwrap(try focus["pullPush"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 2)
        for item in cases {
            let colour = try Self.image(item["colour"])
            let coverage = try Self.image(item["coverage"])
            let expected = try Self.image(item["expected"])
            // The golden stores un-premultiplied colour; the fill takes it premultiplied.
            var premultiplied = colour
            for i in 0..<coverage.pixelCount { for c in 0..<3 { premultiplied.data[i * 3 + c] *= coverage.data[i] } }
            let filled = FloatImage.pullPushFill(premultiplied: premultiplied, coverage: coverage)
            let worst = zip(filled.data, expected.data).map { abs($0 - $1) }.max() ?? 1
            XCTAssertLessThanOrEqual(worst, 1e-4, "\(item["name"] ?? "")")
        }
    }

    // MARK: - Whole renders

    func testFocusRenders() throws {
        let focus = try self.focus
        let scene = try XCTUnwrap(focus["scene"] as? [String: Any])
        let imageSRGB = try Self.image(scene["image"])
        let disparity = try Self.image(scene["disparity"])
        let matte = try Self.image(scene["matte"])
        let replacementSRGB = try Self.image(focus["replacement"])
        var linear = imageSRGB
        for i in 0..<linear.data.count { linear.data[i] = ColourMath.toLinear(linear.data[i]) }
        let renders = try XCTUnwrap(focus["renders"] as? [[String: Any]])
        XCTAssertEqual(renders.count, 9)
        for item in renders {
            let name = try XCTUnwrap(item["name"] as? String)
            let p = try XCTUnwrap(item["params"] as? [String: Any])
            var built = RefocusRenderer.buildScene(linear: linear, disparity: disparity,
                                                   matte: (item["matte"] as? Bool) == true ? matte : nil)
            if (item["replacement"] as? Bool) == true {
                var fitted = Self.coverFit(replacementSRGB, width: linear.width, height: linear.height)
                for i in 0..<fitted.data.count { fitted.data[i] = ColourMath.toLinear(fitted.data[i]) }
                built = RefocusRenderer.replacingBackground(built, with: fitted, ownDisparity: nil)
            }
            let params = RefocusRenderer.Parameters(
                targetX: Float(try XCTUnwrap(p["target_x"] as? Double)), targetY: Float(try XCTUnwrap(p["target_y"] as? Double)),
                blur: Float(try XCTUnwrap(p["blur"] as? Double)), focusDepth: Float(try XCTUnwrap(p["focus_depth"] as? Double)),
                style: try XCTUnwrap(EditRecipe.Focus.Style(rawValue: try XCTUnwrap(p["style"] as? String))),
                bokeh: EditRecipe.Focus.Bokeh(rawValue: (p["bokeh"] as? String) ?? "round") ?? .round,
                styleAmount: Float((p["style_amount"] as? Double) ?? 50))
            XCTAssertEqual(Double(RefocusRenderer.focalDisparity(built, x: params.targetX, y: params.targetY)),
                           try XCTUnwrap(item["focalDisparity"] as? Double), accuracy: 1e-3, "\(name) focal disparity")
            XCTAssertEqual(RefocusRenderer.focusIsOnSubject(built, x: params.targetX, y: params.targetY),
                           try XCTUnwrap(item["subjectInFocus"] as? Bool), "\(name) subject in focus")
            let out = RefocusRenderer.render(built, params)
            var encoded = out
            for i in 0..<encoded.data.count { encoded.data[i] = ColourMath.toEncoded(min(max(encoded.data[i], 0), 1)) }
            let expected = try Self.image(item["expected"])
            let deltas = Self.deltaE2000(encoded, expected).sorted()
            let mean = deltas.reduce(0, +) / Double(deltas.count)
            let p99 = deltas[Int(Double(deltas.count - 1) * 0.99)]
            XCTAssertLessThanOrEqual(mean, 1.0, "\(name): ΔE00 mean \(mean)")
            XCTAssertLessThanOrEqual(p99, 4.0, "\(name): ΔE00 p99 \(p99)")
        }
    }

    /// refocus.cover_fit: aspect-fill with cv2 INTER_AREA (its enlargement weights), crop at the centre.
    static func coverFit(_ image: FloatImage, width: Int, height: Int) -> FloatImage {
        let factor = max(Double(height) / Double(image.height), Double(width) / Double(image.width))
        let rw = Int((Double(image.width) * factor).rounded(.up)), rh = Int((Double(image.height) * factor).rounded(.up))
        func weights(_ out: Int, _ inCount: Int) -> [(Int, Int, Float)] {
            let scale = Double(inCount) / Double(out), inverse = Double(out) / Double(inCount)
            return (0..<out).map { d in
                var s = Int((Double(d) * scale).rounded(.down))
                var f = Float(Double(d + 1) - Double(s + 1) * inverse)
                f = f <= 0 ? 0 : f - f.rounded(.down)
                if s >= inCount - 1 { s = inCount - 1; f = 0 }
                return (s, min(s + 1, inCount - 1), f)
            }
        }
        let wx = weights(rw, image.width), wy = weights(rh, image.height)
        let top = Int((Double(rh - height) * 0.5).rounded(.toNearestOrEven))
        let left = Int((Double(rw - width) * 0.5).rounded(.toNearestOrEven))
        var out = FloatImage(width: width, height: height, channels: image.channels)
        for y in 0..<height {
            let (y0, y1, fy) = wy[y + top]
            for x in 0..<width {
                let (x0, x1, fx) = wx[x + left]
                for c in 0..<image.channels {
                    func at(_ yy: Int, _ xx: Int) -> Float { image.data[(yy * image.width + xx) * image.channels + c] }
                    let a = at(y0, x0) * (1 - fx) + at(y0, x1) * fx
                    let b = at(y1, x0) * (1 - fx) + at(y1, x1) * fx
                    out.data[(y * width + x) * image.channels + c] = a * (1 - fy) + b * fy
                }
            }
        }
        return out
    }

    // MARK: - Grain

    func testGrainNoiseAndApplication() throws {
        let data = try Data(contentsOf: DevelopParityTests.fixture("shared/contracts/rendering-v2.json"))
        let model = try DevelopModel.load(contractData: data)
        let cases = try XCTUnwrap(try Self.index()["grain"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 4)
        for item in cases {
            let name = try XCTUnwrap(item["name"] as? String)
            let height = try XCTUnwrap(item["height"] as? Int), width = try XCTUnwrap(item["width"] as? Int)
            let p = try XCTUnwrap(item["params"] as? [String: Any])
            let grain = DevelopPixelOperators.GrainEvaluator(
                seed: UInt32(try XCTUnwrap(p["seed"] as? Int)), size: try XCTUnwrap(p["size"] as? Double),
                roughness: try XCTUnwrap(p["roughness"] as? Double), amount: try XCTUnwrap(p["amount"] as? Double) / 100,
                frameWidth: width, frameHeight: height, grainK: model.grainK, referenceLongEdge: model.grainReferenceLongEdge)
            XCTAssertEqual(grain.supersampling, try XCTUnwrap(item["supersampling"] as? Int), name)
            let crop = (item["crop"] as? [Int]) ?? [0, 0, height, width]
            let noise = try Self.floats(item["noise"]).values
            let expected = try Self.floats(item["expected"]).values
            var worstNoise: Double = 0, worstColour: Float = 0
            for row in 0..<crop[2] {
                for column in 0..<crop[3] {
                    let y = crop[0] + row, x = crop[1] + column
                    worstNoise = max(worstNoise, abs(grain.noise(x: x, y: y) - Double(noise[row * crop[3] + column])))
                    var rgb = SIMD3<Float>(Float(0.35 + 0.5 * Double(x) / Double(width)), Float(0.25 + 0.4 * Double(x) / Double(width)),
                                           Float(0.2 + 0.3 * Double(y) / Double(height)))
                    if y < height / 3, x < width / 3 { rgb = SIMD3(0.75, 0.2, 0.15) }
                    let out = grain.apply(rgb, x: x, y: y)
                    let o = (row * crop[3] + column) * 3
                    worstColour = max(worstColour, abs(out.x - expected[o]), abs(out.y - expected[o + 1]), abs(out.z - expected[o + 2]))
                }
            }
            XCTAssertLessThanOrEqual(worstNoise, 1e-4, "\(name) noise")
            XCTAssertLessThanOrEqual(worstColour, 2e-4, "\(name) colour")
        }
    }

    // MARK: - Light leak (revision 2, C4)

    /// The four `lightLeak` goldens: the farthest-corner ray, the premultiplied overlay (zero where
    /// the rotated overlay does not cover the frame) and the screen-blended output, on the same
    /// input ramp as the grain goldens.
    func testLightLeakMatchesTheGoldens() throws {
        let cases = try XCTUnwrap(try Self.index()["lightLeak"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 4)
        for item in cases {
            let name = try XCTUnwrap(item["name"] as? String)
            let height = try XCTUnwrap(item["height"] as? Int), width = try XCTUnwrap(item["width"] as? Int)
            let p = try XCTUnwrap(item["params"] as? [String: Any])
            let style = try XCTUnwrap(EditRecipe.Effects.LightLeak.Style(rawValue: try XCTUnwrap(p["style"] as? String)))
            let leak = EditRecipe.Effects.LightLeak(enabled: true, style: style, intensity: try XCTUnwrap(p["intensity"] as? Double),
                                                    x: try XCTUnwrap(p["x"] as? Double), y: try XCTUnwrap(p["y"] as? Double),
                                                    rotation: try XCTUnwrap(p["rotation"] as? Double))
            let evaluator = try XCTUnwrap(LightLeakEvaluator(leak, frameWidth: width, frameHeight: height))
            XCTAssertEqual(evaluator.farthestCorner, try XCTUnwrap(item["farthestCornerPx"] as? Double), accuracy: 1e-4, name)
            let premultiplied = try Self.floats(item["premultiplied"]).values
            let expected = try Self.floats(item["expected"]).values
            var worstOverlay = 0.0, worstOutput: Float = 0
            for y in 0..<height {
                for x in 0..<width {
                    let o = (y * width + x) * 3
                    let overlay = evaluator.premultiplied(x: x, y: y) ?? .zero
                    for c in 0..<3 { worstOverlay = max(worstOverlay, abs(overlay[c] - Double(premultiplied[o + c]))) }
                    var rgb = SIMD3<Float>(Float(0.35 + 0.5 * Double(x) / Double(width)), Float(0.25 + 0.4 * Double(x) / Double(width)),
                                           Float(0.2 + 0.3 * Double(y) / Double(height)))
                    if y < height / 3, x < width / 3 { rgb = SIMD3(0.75, 0.2, 0.15) }
                    let out = evaluator.apply(rgb, x: x, y: y)
                    worstOutput = max(worstOutput, abs(out.x - expected[o]), abs(out.y - expected[o + 1]), abs(out.z - expected[o + 2]))
                }
            }
            XCTAssertLessThanOrEqual(worstOverlay, 2e-4, "\(name) premultiplied")
            XCTAssertLessThanOrEqual(worstOutput, 2e-4, "\(name) output")
        }
    }

    /// The `selectiveColour` goldens (rendering-v2 revision 4): the sampled picks, the keep weights and the output.
    func testSelectiveColourMatchesTheGoldens() throws {
        let cases = try XCTUnwrap(try Self.index()["selectiveColour"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 5)
        for item in cases {
            let name = try XCTUnwrap(item["name"] as? String)
            let height = try XCTUnwrap(item["height"] as? Int), width = try XCTUnwrap(item["width"] as? Int)
            let p = try XCTUnwrap(item["params"] as? [String: Any])
            let input = try Self.floats(item["input"]).values
            let keepExpected = try Self.floats(item["keep"]).values
            let expected = try Self.floats(item["expected"]).values
            let picks = try XCTUnwrap(item["picks"] as? [[Double]])
            let colours = try XCTUnwrap(p["colours"] as? [[Double]])
            for (pick, colour) in zip(picks, colours) {
                let sampled = SelectiveColourEvaluator.sample(width: width, height: height, xFraction: pick[0], yFraction: pick[1]) { x, y in
                    let o = (y * width + x) * 3
                    return DevelopGlobalProgram.srgbToLinear(SIMD3<Double>(Double(input[o]), Double(input[o + 1]), Double(input[o + 2])))
                }
                for c in 0..<3 { XCTAssertEqual(sampled[c], colour[c], accuracy: 1e-4, "\(name) pick") }
            }
            let selective = EditRecipe.Effects.SelectiveColour(
                colours: colours.map { .init(oklab: SIMD3($0[0], $0[1], $0[2]), x: 0, y: 0) },
                range: try XCTUnwrap(p["range"] as? Double), strength: try XCTUnwrap(p["strength"] as? Double))
            let evaluator = SelectiveColourEvaluator(selective)
            XCTAssertEqual(evaluator == nil, colours.isEmpty, name)
            var worstKeep = 0.0, worstOutput: Float = 0
            for i in 0..<(width * height) {
                let rgb = SIMD3<Float>(input[i * 3], input[i * 3 + 1], input[i * 3 + 2])
                let lab = DevelopGlobalProgram.linearToOKLab(DevelopGlobalProgram.srgbToLinear(SIMD3<Double>(rgb)))
                worstKeep = max(worstKeep, abs((evaluator?.keep(lab) ?? 0) - Double(keepExpected[i])))
                let out = evaluator?.apply(rgb) ?? rgb
                worstOutput = max(worstOutput, abs(out.x - expected[i * 3]), abs(out.y - expected[i * 3 + 1]), abs(out.z - expected[i * 3 + 2]))
            }
            XCTAssertLessThanOrEqual(worstKeep, 2e-4, "\(name) keep")
            XCTAssertLessThanOrEqual(worstOutput, 2e-4, "\(name) output")
        }
    }

    /// The `foreground` goldens (rendering-v2 revision 5): background.replace's foreground estimate and composite.
    func testForegroundEstimateMatchesTheGoldens() throws {
        let cases = try XCTUnwrap(try Self.index()["foreground"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 2)
        for item in cases {
            let name = try XCTUnwrap(item["name"] as? String)
            let height = try XCTUnwrap(item["height"] as? Int), width = try XCTUnwrap(item["width"] as? Int)
            let image = FloatImage(width: width, height: height, channels: 3, data: try Self.floats(item["image"]).values)
            let alpha = FloatImage(width: width, height: height, channels: 1, data: try Self.floats(item["alpha"]).values)
            let expected = try Self.floats(item["foreground"]).values
            let composite = try Self.floats(item["composite"]).values
            let replacement = try XCTUnwrap(item["replacement"] as? [Double]).map(Float.init)
            let foreground = ForegroundEstimate.estimate(image, alpha: alpha)
            var worstF: Float = 0, worstComposite: Float = 0
            for i in 0..<expected.count {
                worstF = max(worstF, abs(foreground.data[i] - expected[i]))
                let a = alpha.data[i / 3]
                worstComposite = max(worstComposite, abs(foreground.data[i] * a + replacement[i % 3] * (1 - a) - composite[i]))
            }
            XCTAssertLessThanOrEqual(worstF, 1e-4, "\(name) foreground")
            XCTAssertLessThanOrEqual(worstComposite, 1e-4, "\(name) composite")
        }
    }

    // MARK: - CIEDE2000

    static func deltaE2000(_ a: FloatImage, _ b: FloatImage) -> [Double] {
        (0..<a.pixelCount).map { i in
            ciede2000(lab(a.data[i * 3], a.data[i * 3 + 1], a.data[i * 3 + 2]), lab(b.data[i * 3], b.data[i * 3 + 1], b.data[i * 3 + 2]))
        }
    }

    /// sRGB (encoded) → CIELAB, D65.
    static func lab(_ r: Float, _ g: Float, _ b: Float) -> (Double, Double, Double) {
        func lin(_ v: Float) -> Double { let x = Double(v); return x <= 0.04045 ? x / 12.92 : pow((x + 0.055) / 1.055, 2.4) }
        let (lr, lg, lb) = (lin(r), lin(g), lin(b))
        let x = (0.4124564 * lr + 0.3575761 * lg + 0.1804375 * lb) / 0.95047
        let y = 0.2126729 * lr + 0.7151522 * lg + 0.0721750 * lb
        let z = (0.0193339 * lr + 0.1191920 * lg + 0.9503041 * lb) / 1.08883
        func f(_ t: Double) -> Double { t > 216.0 / 24389 ? cbrt(t) : (24389.0 / 27 * t + 16) / 116 }
        return (116 * f(y) - 16, 500 * (f(x) - f(y)), 200 * (f(y) - f(z)))
    }

    static func ciede2000(_ p: (Double, Double, Double), _ q: (Double, Double, Double)) -> Double {
        let (l1, a1, b1) = p, (l2, a2, b2) = q
        let c1 = (a1 * a1 + b1 * b1).squareRoot(), c2 = (a2 * a2 + b2 * b2).squareRoot()
        let cMean = (c1 + c2) / 2
        let g = 0.5 * (1 - (pow(cMean, 7) / (pow(cMean, 7) + pow(25, 7))).squareRoot())
        let a1p = (1 + g) * a1, a2p = (1 + g) * a2
        let c1p = (a1p * a1p + b1 * b1).squareRoot(), c2p = (a2p * a2p + b2 * b2).squareRoot()
        func hue(_ b: Double, _ a: Double) -> Double {
            if a == 0 && b == 0 { return 0 }
            let h = atan2(b, a) * 180 / .pi
            return h < 0 ? h + 360 : h
        }
        let h1p = hue(b1, a1p), h2p = hue(b2, a2p)
        let dLp = l2 - l1, dCp = c2p - c1p
        var dhp = 0.0
        if c1p * c2p != 0 {
            dhp = h2p - h1p
            if dhp > 180 { dhp -= 360 } else if dhp < -180 { dhp += 360 }
        }
        let dHp = 2 * (c1p * c2p).squareRoot() * sin(dhp * .pi / 360)
        let lMean = (l1 + l2) / 2, cpMean = (c1p + c2p) / 2
        var hpMean = h1p + h2p
        if c1p * c2p != 0 {
            if abs(h1p - h2p) > 180 { hpMean = h1p + h2p < 360 ? (h1p + h2p + 360) / 2 : (h1p + h2p - 360) / 2 } else { hpMean = (h1p + h2p) / 2 }
        }
        let t = 1 - 0.17 * cos((hpMean - 30) * .pi / 180) + 0.24 * cos(2 * hpMean * .pi / 180)
            + 0.32 * cos((3 * hpMean + 6) * .pi / 180) - 0.20 * cos((4 * hpMean - 63) * .pi / 180)
        let dTheta = 30 * exp(-pow((hpMean - 275) / 25, 2))
        let rc = 2 * (pow(cpMean, 7) / (pow(cpMean, 7) + pow(25, 7))).squareRoot()
        let sl = 1 + 0.015 * pow(lMean - 50, 2) / (20 + pow(lMean - 50, 2)).squareRoot()
        let sc = 1 + 0.045 * cpMean, sh = 1 + 0.015 * cpMean * t
        let rt = -sin(2 * dTheta * .pi / 180) * rc
        return (pow(dLp / sl, 2) + pow(dCp / sc, 2) + pow(dHp / sh, 2) + rt * (dCp / sc) * (dHp / sh)).squareRoot()
    }
}
